//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.4927
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace MySquare.FourSquare {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class venues {
        
        private venuesGroup[] groupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("group")]
        public venuesGroup[] group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class venuesGroup {
        
        private venuesGroupVenue[] venueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("venue")]
        public venuesGroupVenue[] venue {
            get {
                return this.venueField;
            }
            set {
                this.venueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class venuesGroupVenue {
        
        private uint idField;
        
        private string nameField;
        
        private venuesGroupVenuePrimarycategory primarycategoryField;
        
        private string addressField;
        
        private string crossstreetField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private decimal geolatField;
        
        private decimal geolongField;
        
        private venuesGroupVenueStats statsField;
        
        private string twitterField;
        
        private ulong phoneField;
        
        private bool phoneFieldSpecified;
        
        private ushort distanceField;
        
        /// <remarks/>
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public venuesGroupVenuePrimarycategory primarycategory {
            get {
                return this.primarycategoryField;
            }
            set {
                this.primarycategoryField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string crossstreet {
            get {
                return this.crossstreetField;
            }
            set {
                this.crossstreetField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public decimal geolat {
            get {
                return this.geolatField;
            }
            set {
                this.geolatField = value;
            }
        }
        
        /// <remarks/>
        public decimal geolong {
            get {
                return this.geolongField;
            }
            set {
                this.geolongField = value;
            }
        }
        
        /// <remarks/>
        public venuesGroupVenueStats stats {
            get {
                return this.statsField;
            }
            set {
                this.statsField = value;
            }
        }
        
        /// <remarks/>
        public string twitter {
            get {
                return this.twitterField;
            }
            set {
                this.twitterField = value;
            }
        }
        
        /// <remarks/>
        public ulong phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool phoneSpecified {
            get {
                return this.phoneFieldSpecified;
            }
            set {
                this.phoneFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ushort distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class venuesGroupVenuePrimarycategory {
        
        private uint idField;
        
        private string fullpathnameField;
        
        private string nodenameField;
        
        private string iconurlField;
        
        /// <remarks/>
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string fullpathname {
            get {
                return this.fullpathnameField;
            }
            set {
                this.fullpathnameField = value;
            }
        }
        
        /// <remarks/>
        public string nodename {
            get {
                return this.nodenameField;
            }
            set {
                this.nodenameField = value;
            }
        }
        
        /// <remarks/>
        public string iconurl {
            get {
                return this.iconurlField;
            }
            set {
                this.iconurlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class venuesGroupVenueStats {
        
        private byte herenowField;
        
        /// <remarks/>
        public byte herenow {
            get {
                return this.herenowField;
            }
            set {
                this.herenowField = value;
            }
        }
    }
}
